version: '3.8'

services:
  app:
    build:
      context: ../part5/.
      dockerfile: Dockerfile
    networks:
      - app_network

  nginx_proxy:
    image: nginx
    depends_on:
      - app
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx_proxy.conf:/etc/nginx/nginx.conf
    networks:
      - app_network

networks:
  app_network:
    driver: bridge